# config.yaml
credentials:
  usernames:
    # Usuário 1 (corresponde à primeira senha)
    rafael:
      email: posvendas01@topema.com
      name: Rafael Topema
      password: '$2b$12$Z761qMNWUhhSbW/z2vADTO20exZCk7UsyiPZSBMimTOSia0b7rSHG' # <-- PRIMEIRO HASH AQUI

    # Usuário 2 (corresponde à segunda senha)
    admin:
      email: rmbarboza.ltda@gmail.com
      name: Rafael Ltda
      password: '$2b$12$bW3bapyydn5Dm6XW8HXXCeageLKTWzrGAtVdfkk5NvqkpMuF3MgbS' # <-- SEGUNDO HASH AQUI

    # Usuário 3 (corresponde à terceira senha)
    visitante:
      email: rmbarboza.90@gmail.com
      name: Rafael Barboza
      password: '$2b$12$/hnTJB1gIQa09T8RCBOE7ezMLGipPrnyIc/zjlGXEEteNlMv1N8tW' # <-- TERCEIRO HASH AQUI

cookie:
  expiry_days: 30
  key: 'spfc' # Mude para qualquer string aleatória
  name: 'cookie_dashboard_garantia' # Nome único para o cookie

# --- ADICIONE ESTA SEÇÃO ---
preauthorized:
  emails: []
