name: Atualizar Dados e Dashboard

on:
  workflow_dispatch:

  schedule:
    # Roda a cada 30 minutos, das 07:00 às 17:30 BRT (10:00-20:00 UTC)
    - cron: '0,30 10-20 * * *'
    # Roda uma última vez às 18:00 BRT (21:00 UTC)
    - cron: '0 21 * * *'

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar script de atualização de dados
        run: python update_data.py

      - name: Commit e Push dos arquivos atualizados
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🚀 [Auto] Sincronização de dados e código"
